### ISSUE TITLE
Refactor: 면접 결과 - 피드백 페이지 연결

### ISSUE THREAD

**Issue by shdbwls66** [six-do-string/jobshin#109]
### 💼 작업 설명
실전모드는 면접 결과를 보여준 후, levelFeedback 페이지와 연결,
연습모드는 면접 결과를 보여준 후, 메인 페이지와 연결
실전모드 생성 메서드, createQuestions()를 createQuestions2() 코드형식과 동일하게 수정
 
### ✅ To-do

- [ ] InterviewThymeleafController의 getInterviewResult() 메서드 수정
- [ ] createQuestions() 메서드 수정
- [ ] 모드 종류에 따라 각 페이지와 연결되도록 수정
