### ISSUE TITLE
Feat: AiFeedback 프론트 화면 작업

### ISSUE THREAD

**Issue by wions37** [six-do-string/jobshin#12]
### 💼 작업 설명
AiFeedback 면접결과 피드백 화면 

### ✅ To-do
- [ ] AiFeedback 프론트 작업
- [ ] AiFeedback html 작업
- [ ] AiFeedback css.js 작업
