### ISSUE TITLE
Design: 면접 질문 화면 링크 추가, 면접 입장 페이지 화면 수정

### ISSUE THREAD

**Issue by shdbwls66** [six-do-string/jobshin#128]
### 💼 작업 설명
면접 입장 페이지 화면 수정과 면접 질문 화면의 '처음으로 돌아가기' 링크를 활성화하였습니다.
결과 페이지의 토글 버튼 수정하였습니다.
interview Dto 디렉토리의 interviewLevel 파일 삭제하고 유저 레벨 업데이트 메서드(updateUserLevel(), updateLevel()) 파라미터 타입을 Double로 수정하였습니다.
 
### ✅ To-do

- [ ] 면접 입장 페이지 화면 수정, 결과 페이지의 토글 버튼 수정
- [ ] 면접 질문 화면의 처음으로 돌아가기 링크 활성화
- [ ] interview Dto 디렉토리의 interviewLevel 파일 삭제
- [ ] 유저 레벨 업데이트 메서드(updateUserLevel(), updateLevel()) 파라미터 타입을 Double로 수정
