### ISSUE TITLE
Feat: 면접 이력 조회 기능

### ISSUE THREAD

**Issue by yub-bi** [six-do-string/jobshin#13]
### 💼 작업 설명
면접 이력 조회 기능
 
### ✅ To-do

- [ ] 인터뷰 레포지토리 설정
- [ ] 면접 이력 목록 조회
- [ ] 면접 이력 상세 조회
