### ISSUE TITLE
Refactor: 면접 문제 반환하는 뷰의 url 수정 (화면도 일부 수정)

### ISSUE THREAD

**Issue by shdbwls66** [six-do-string/jobshin#131]
### 💼 작업 설명
면접 문제 반환하는 뷰의 url을 수정하였습니다. (화면도 일부 수정)
 
### ✅ To-do

- [ ] 문제 생성 뷰 url 수정
- [ ] 결과 뷰 url 수정
- [ ] 문제 뷰에서 연습모드는 카테고리가 뜨도록 수정
