### ISSUE TITLE
Design: 비정상적으로 종료된 인터뷰 이어히기 버튼 추가, 사용하지 않는 코드 및 파일 정리, 상단바 디자인 수정

### ISSUE THREAD

**Issue by whwnsgh0258** [six-do-string/jobshin#144]
### 💼 작업 설명
- 비정상적으로 종료된 인터뷰 이어히기 버튼 추가
- 사용하지 않는 코드 및 파일 정리
  - Post 폴더 및 하위 파일
  - 회원 정보 수정, 인터뷰 이력 및 상세보기 페이지 사이드바 링크
- 상단바 디자인 수정
  - 기존 회원의 아이디를 노출하는 상태에서 닉네임 노출로 변경
 
### ✅ To-do

- [x] 비정상적으로 종료된 인터뷰 이어히기 버튼 추가
- [x] 사용하지 않는 코드 및 파일 정리
- [x] 상단바 디자인 수정
