### ISSUE TITLE
Refactor: InterviewDetail 관련 코드 리팩터링

### ISSUE THREAD

**Issue by yunjunho97** [six-do-string/jobshin#151]
### 💼 작업 설명
InterviewDetail 관련 코드 리팩터링
 
### ✅ To-do

- [ ] InterviewDetail - Builder어노테이션 삭제, Size -> Colunm으로 어노테이션 통일
- [ ] InterviewDetailRepository - Repository어노테이션 삭제
- [ ] InterviewDetailService - 자주 사용되는 고정된 변수들을 상수처리
