### ISSUE TITLE
Design: 이력 조회 리스트, 헤더, 로그인 및 회원가입 에러 메세지 수정

### ISSUE THREAD

**Issue by whwnsgh0258** [six-do-string/jobshin#153]
### 💼 작업 설명
- 이력 조회 리스트
  - 상세 페이지로 넘어가는 링크 텍스트 디자인 변경
  - 0번 페이지가 나오는 부분 수정 **(페이지 버튼 리스트가 있어야 버튼이 나오도록 변경)**
- 헤더 로그아웃 버튼 포인터 추가
- 로그인, 회원 가입 에러 메세지 디자인 수정
 
### ✅ To-do

- [x] 이력 조회 리스트 디자인 수정
- [x] 헤더 로그아웃 버튼 포인터 추가
- [x] 로그인, 회원 가입 에러 메세지 디자인 수정
