### ISSUE TITLE
Refactor: 유저 이메일, 비밀번호 유효성 검증 강화, 인터뷰 리스트 완료되지 않은 인터뷰 순으로 정렬, 미사용 어노테이션 삭제

### ISSUE THREAD

**Issue by whwnsgh0258** [six-do-string/jobshin#162]
### 💼 작업 설명
- 유저 이메일, 비밀번호 유효성 검증 강화
- 인터뷰 리스트 완료되지 않은 인터뷰 순으로 정렬
- 미사용 어노테이션 삭제
 
### ✅ To-do

- [x] 유저 이메일, 비밀번호 유효성 검증 강화
- [x] 인터뷰 리스트 완료되지 않은 인터뷰 순으로 정렬
- [x] 미사용 어노테이션 삭제
