### ISSUE TITLE
Design: 로그인 회원가입 에러 메세지 크기 수정, 인터뷰 이력 리스트 level 컬럼및 버튼 디자인 추가, 인터뷰 상세 토글 기능 추가

### ISSUE THREAD

**Issue by whwnsgh0258** [six-do-string/jobshin#164]
### 💼 작업 설명
- 로그인 회원가입 에러 메세지 크기 수정
- 인터뷰 이력 리스트 level 컬럼및 버튼 디자인 추가
- 인터뷰 상세 토글 기능 추가
 
### ✅ To-do

- [x] 로그인 회원가입 에러 메세지 크기 수정
- [x] 인터뷰 이력 리스트 level 컬럼및 버튼 디자인 추가
- [x] 인터뷰 상세 토글 기능 추가
