### ISSUE TITLE
Test: 프로덕트 코드 리펙토링으로 인한 테스트 코드 수정

### ISSUE THREAD

**Issue by LeeJeongSeok** [six-do-string/jobshin#165]
### 💼 작업 설명
프로덕트 코드 리펙토링으로 인한 테스트 코드 수정
 
### ✅ To-do

- [ ] Builder 패턴으로 생성하던 객체를 각 상황에 맞는 생성자 만들기
- [ ] 실제 DB 말고 H2 데이터베이스를 사용할 수 있도록 수정
- [ ] 실제 DB에 insert 되고 delete 하는 과정 수정
