### ISSUE TITLE
feat: security 및 User 엔티티 관련 로직 작성

### ISSUE THREAD

**Issue by whwnsgh0258** [six-do-string/jobshin#17]
### 💼 작업 설명
- security 인증 로직 작성
- User 도메인 회원가입 로직 작성
 
### ✅ To-do
- [ ] User Entity 작성
- [ ] Security 회원가입 시 비밀번호 암호화
- [ ] UserService, UserController 회원가입 로직 작성
