### ISSUE TITLE
Refactor: 모의면접 에러 메세지 수정 및 에러 부분 제외한 console.log() 제거

### ISSUE THREAD

**Issue by shdbwls66** [six-do-string/jobshin#184]
### 💼 작업 설명
모의면접 에러 메세지 수정 및 에러 부분 제외한 console.log() 제거
 
### ✅ To-do

- [ ] 에러 부분은 모두 alert 창을 통애 메세지 던지도록 수정
- [ ] 로딩 부분 에러 메세지 수정
- [ ] 불필요한 console.log() 제거
