### ISSUE TITLE
feat: Post Entity와 User테이블 연관관계 설정, 시큐리티 관련 설정 추가

### ISSUE THREAD

**Issue by yunjunho97** [six-do-string/jobshin#23]
### 💼 작업 설명
User테이블이 구현되어서 기존에 독립적으로 개발했던 Post쪽을 User와 연결하는 작업
 
### ✅ To-do

- [ ] Post클래스에 연관관계 맵핑 추가
- [ ] PostService클래스에 현재 세션의 사용자 정보를 가져오는 코드 추가
- [ ] 기존에 작성되었던 게시글 등록 메서드에 유저정보를 넣어주는 코드 추가
