### ISSUE TITLE
feat: 시큐리티 파일 의존성 수정 및 코드 정렬, User SSR 방식으로 회원가입 기능 변경 및 로그인 기능 추가

### ISSUE THREAD

**Issue by whwnsgh0258** [six-do-string/jobshin#30]
### 💼 작업 설명
시큐리티 파일 의존성 수정 및 코드 정렬, User SSR 방식으로 회원가입 기능 변경 및 로그인 기능 추가
 
### ✅ To-do

- [ ] 시큐리티 의존성 수정
- [ ] RESTful 방식에서 SSR 방식으로 회원가입 기능 변경
- [ ] 로그인 기능 추가
