### ISSUE TITLE
feat: User 회원 정보 수정 및 삭제 기능 추가, User Entity 및 Security 변수 변경, HomeController에 메인페이지 생성

### ISSUE THREAD

**Issue by whwnsgh0258** [six-do-string/jobshin#42]
### 💼 작업 설명
- User Entity 필드명 변경 **(email, username)** -> **(username, nickname)** 
- Security 변수명 변경 **(email, username)** -> **(username, nickname)**
- User 회원정보 수정 및 삭제 기능 추가
- HomeController에 mainPage 생성 및 "/" 경로는 자동으로 mainPage로 redirect되게 설정

### ✅ To-do
- [x] User Entity 필드명 변경 **(email, username)** -> **(username, nickname)** 
- [x] User 회원정보 수정 및 삭제 기능 추가
- [x] HomeController에 mainPage 생성 및 "/" 경로는 자동으로 mainPage로 redirect되게 설정
