### ISSUE TITLE
Feat: 사용자로부터 답변 받아오는 기능 추가

### ISSUE THREAD

**Issue by yunjunho97** [six-do-string/jobshin#46]
### 💼 작업 설명
사용자로부터 답변을 받으면 다음 질문을 보내주고 해당 답변에 대해서는 비동기적으로 처리
 
### ✅ To-do

- [x] 서버-클라이언트간에 질문답변을 주고받을 dto추가
- [x] 사용자로부터 답변을 받으면 다음 질문을 전달
- [x] 사용자로부터 받은 답변과, 해당 답변을 ai에 보내고 받아온 피드백 db에 저장
- [x] 주석처리 해놓은 부분 삭제
- [x] 사용하지 않는 클래스, 메서드 삭제
- [x] 리팩터링 완료 후 정상동작 하는지 테스트 진행
