### ISSUE TITLE
Feat: 사용자 답변, 예시 답변 생성 메서드 추가

### ISSUE THREAD

**Issue by shdbwls66** [six-do-string/jobshin#47]
### 💼 작업 설명
사용자 답변, 예시 답변 생성하는 메서드 추가하기

### ✅ To-do

- [ ] AlenService - 예시 답변 날리는 메서드 추가
- [ ] 사용자 답변 생성하는 메서드 추가
- [ ] 예시 답변 생성하는 메서드 추가
