### ISSUE TITLE
Refactor: User Controller, Security API EndPoint 및 링크 리펙토링

### ISSUE THREAD

**Issue by whwnsgh0258** [six-do-string/jobshin#56]
### 💼 작업 설명
- User Controller, Security API EndPoint 및 링크 리펙토링
- 로그인, 회원가입, 회원정보 수정, 헤더 링크 리펙토링
 
### ✅ To-do

- [ ] User Controller API EndPoint 리펙토링
- [ ] Security API EndPoint 리펙토링
- [ ] 로그인, 회원가입, 회원정보 수정, 헤더 링크 리펙토링
