### ISSUE TITLE
Feat: 면접 페이지 뷰 설계

### ISSUE THREAD

**Issue by shdbwls66** [six-do-string/jobshin#58]
### 💼 작업 설명
면접 페이지 뷰 설계
면접 관련 RESTApi 데이터 불러오기
 
### ✅ To-do

- [ ] 면접 입장 페이지 뷰 설계
- [ ] 면접 질문 페이지 뷰 설계
- [ ] interview 관련 RESTApi 뷰 연동
