### ISSUE TITLE
Feat: Interview 와 User 테이블 연결

### ISSUE THREAD

**Issue by yunjunho97** [six-do-string/jobshin#59]
### 💼 작업 설명
Interview와 User 테이블 연결
면접 카테고리 임의로 넣던 부분을 실제로 카테고리 리스트로 생성
실전모드 / 연습모드 분리
 
### ✅ To-do

- [ ] Interview도메인에서 생성자에 User추가
- [ ] InterviewService에서 현재 세션의 유저 정보를 Interview의 User로 저장
- [ ] Category타입으로 랜덤 리스트 생성 메서드 추가(실전모드)
- [ ] RequestParam으로 받아온 카테고리로 리스트 생성(연습모드)
