### ISSUE TITLE
게시글 등록

### ISSUE THREAD

**Issue by yunjunho97** [six-do-string/jobshin#6]
### 💼 작업 설명
게시글 등록을 위한 Entity 구성부터 Controller까지 작업
제목, 내용, 작성시간에 null이 들어오는 경우에 대한 예외처리 작업
 
### ✅ To-do

- [ ] 게시글 테이블 Entity 작성
- [ ] 클라이언트로부터 받을 데이터를 처리할 DTO 작성
- [ ] PostRepository 인터페이스 작성
- [ ] PostService에서 게시글 저장 메서드 작성
- [ ] PostController에서 PostMapping을 받을 메서드 작성
- [ ] GlobalExceptionHandler에서 예외 처리 작성
