### ISSUE TITLE
Test: 테스트코드 - UserRepositoryTest 

### ISSUE THREAD

**Issue by wions37** [six-do-string/jobshin#79]
### ✅ To-do
- [ ] 회원 가입테스트
- [ ] 회원 수정 테스트
- [ ] 회원 탈퇴 테스트 
- [ ] 마이페이지 - 면접 이력 확인  테스트 
- [ ] 마이페이지 - 면접 상세 이력  테스트

**Comment by wions37** [comment]
RepositoryTest 작성
