### ISSUE TITLE
Test: 테스트코드 - UserServiceTest

### ISSUE THREAD

**Issue by wions37** [six-do-string/jobshin#83]
### 💼 작업 설명
테스트코드 - UserServiceTest
 
### ✅ To-do

- [x] 회원 가입 성공 테스트"
- [x] 회원 정보 조회 성공 테스트
- [x] 회원 정보 조회 실패 테스트
- [x] 회원 정보 수정 성공 테스트
- [x] 회원 정보 중복 확인 테스트
- [x] 회원 탈퇴 성공 테스트
- [x] 회원탈퇴 예외 처리
- [x] 모의 면접 리스트 페이징 처리 테스트

**Comment by wions37** [comment]
추가 작성사항이 아직 남아 리오픈 합니다.

**Comment by wions37** [comment]
추가 할 부분이 생겨서 리오픈
