### ISSUE TITLE
Feat: LevelFeedback 화면 작업

### ISSUE THREAD

**Issue by wions37** [six-do-string/jobshin#9]
### 💼 작업 설명
모의면접 완료후 피드백선택 페이지 화면
 
### ✅ To-do
- [ ] LevelFeedback 프론트 작업
- [ ] LevelFeedback  html 작업
- [ ] LevelFeedback  css.js 작업

**Comment by wions37** [comment]
해당 완료 되어 닫기 처리합니다.
