### ISSUE TITLE
Test: 테스트코드 - InterviewRepositoryTest 구현

### ISSUE THREAD

**Issue by wions37** [six-do-string/jobshin#90]
### 💼 작업 설명
테스트코드 - InterviewRepositoryTest 작성
 
### ✅ To-do

- [x] 사용자의 Practice/ REAL 모드 인터뷰 조회 테스트
- [x] Interview ID로 InterviewDetail 조회 테스트
- [x] 인터뷰에 상세 내용이 확인하는 테스트
