### ISSUE TITLE
Refactor: Interview 관련 코드 리팩토링

### ISSUE THREAD

**Issue by yunjunho97** [six-do-string/jobshin#96]
### 💼 작업 설명
중복코드 제거
안쓰는 주석처리 된 코드 제거
메서드 명 변경
 
### ✅ To-do

- [ ] 컨트롤러에서 RequestMapping으로 중복 제거
- [ ] 도메인에서 createAt -> createdAt으로 수정, 사이드이펙트 수정
- [ ] 레파지토리에서 Repository어노테이션 삭제
- [ ] 서비스에서 메서드명 수정, 사이드이펙트 수정
